import os
import json
import logging
from typing import Dict, Any
import google.generativeai as genai

logger = logging.getLogger("OTC_Enterprise_Quant.VisionGemini")

class VisionGeminiEngine:
    """
    Multimodal Vision Engine utilizing Google Gemini AI.
    Analyzes candlestick screenshots to extract price action patterns,
    Support/Resistance zones, and Smart Money Concepts (SMC) variables.
    """

    def __init__(self, api_key: str = None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            logger.warning("GEMINI_API_KEY environment variable not explicitly set.")
        else:
            genai.configure(api_key=self.api_key)

        # Using standard multimodal vision model configuration
        self.model = genai.GenerativeModel("gemini-1.5-flash")

    def _build_prompt(self) -> str:
        """
        Constructs a strict system prompt instructing Gemini to return valid JSON.
        """
        return """
        You are an elite quantitative chart analysis system specializing in OTC binary options and price action trading.
        Analyze the provided chart image thoroughly and output ONLY a raw JSON object with NO markdown formatting, NO code blocks, and NO explanatory text outside JSON.

        Extract the following attributes precisely:
        {
            "asset_pair": "EUR/USD-OTC" (or detected pair, default 'UNKNOWN_OTC'),
            "data_1d": {
                "primary_trend": "STRONG_BULLISH" | "WEAK_BULLISH" | "CONSOLIDATION" | "WEAK_BEARISH" | "STRONG_BEARISH"
            },
            "data_1h": {
                "primary_trend": "STRONG_BULLISH" | "WEAK_BULLISH" | "CONSOLIDATION" | "WEAK_BEARISH" | "STRONG_BEARISH",
                "rejection_zone": "UPPER_REJECTION" | "LOWER_REJECTION" | "NEUTRAL",
                "volatility_score": float between 0.0 and 100.0,
                "support_resistance_count": integer,
                "fvg_detected": boolean,
                "fvg_type": "BULLISH_FVG" | "BEARISH_FVG" | "NONE",
                "liquidity_sweep": boolean,
                "sweep_side": "BUY_SIDE_LIQUIDITY" | "SELL_SIDE_LIQUIDITY" | "NONE",
                "order_block_detected": boolean,
                "order_block_zone": "BULLISH_ORDER_BLOCK" | "BEARISH_ORDER_BLOCK" | "NONE",
                "recommended_direction": "UP" | "DOWN" | "NO_TRADE"
            }
        }
        """

    def analyze_chart(self, image_path: str) -> Dict[str, Any]:
        """
        Uploads image file to Gemini Vision API and returns parsed quantitative chart data.
        """
        if not os.path.exists(image_path):
            raise FileNotFoundError(f"Image path not found: {image_path}")

        try:
            logger.info(f"Processing chart image with Gemini Vision: {image_path}")
            
            # Load local image for API
            with open(image_path, "rb") as img_file:
                image_data = img_file.read()

            image_part = {
                "mime_type": "image/png",  # Accepts standard png/jpeg formats
                "data": image_data
            }

            prompt = self._build_prompt()
            response = self.model.generate_content([prompt, image_part])

            raw_text = response.text.strip()

            # Clean markdown JSON wraps if generated by AI
            if raw_text.startswith("```json"):
                raw_text = raw_text[7:]
            if raw_text.startswith("```"):
                raw_text = raw_text[3:]
            if raw_text.endswith("```"):
                raw_text = raw_text[:-3]

            parsed_data = json.loads(raw_text.strip())
            logger.info("Successfully extracted quantitative vision data from chart image.")
            return parsed_data

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON response from Gemini Vision: {str(e)}")
            raise ValueError("Vision AI output format invalid. Expected pure JSON.")
        except Exception as e:
            logger.error(f"Error during Gemini chart evaluation: {str(e)}")
            raise e

